---

# Put /etc/elinks.conf in place from template

  - name: upload elinks.conf from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/elinks_conf/templates/elinks_conf.j2"
      dest: /etc/elinks.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
