---

# Put lvm configuration into place using templates

  - name: upload /etc/lvm/lvm.conf into place from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/lvm_conf/templates/lvm.conf.j2"
      dest: /etc/lvm/lvm.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
