---

# Put a node_exporter in place from template - made by JB

  - name: upload node_exporter options file from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/node-exporter-install/templates/node_exporter.j2"
      dest: /etc/sysconfig/node_exporter
      owner: root
      group: root
      mode: '0640'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
    notify: restart_node_exporter
    when: ansible_hostname not in 'sl-uoka1t, sl-uokda2t, sl-uokda3t, sl-uokda4t, sl-uokdi1t, sl-uokdi2t, sl-uokdi3t, sl-uokdm1t, sl-uokdm2t, sl-uokdm3t'
