---

# Put configuration into place using templates

  - name: upload /etc/yum/protected.d/systemd.conf into place from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/protected_conf/templates/systemd.conf.j2"
      dest: /etc/yum/protected.d/systemd.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0

