---

# Put configuration into place using templates

  - name: upload /etc/gss/mech.d/gssproxy.conf into place from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/gss_mech_conf/templates/gssproxy.conf.j2"
      dest: /etc/gss/mech.d/gssproxy.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0

