---

# Put /etc/host.conf in place from template

  - name: upload /etc/host.conf from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/host_conf/templates/host_conf.j2"
      dest: /etc/host.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
