---

# Put login defs configuration into place using templates

  - name: upload /etc/login.defs into place from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/login.defs_conf/templates/login.defs.j2"
      dest: /etc/login.defs
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
