---

# Put configuration into place using templates

  - name: upload /etc/depmod.d/dist.conf into place from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/depmod_conf/templates/dist.conf.j2"
      dest: /etc/depmod.d/dist.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0

