---

# Put a sssd.conf in place from template

  - name: upload sssd.conf from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/sssd_conf/templates/sssd_conf.j2"
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: '0700'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: sssd_conf_t
      selevel: s0
    register: sssd_modified
    when: "ansible_hostname not in 'sl-webdmz1d, sl-webdmz1i, sl-webdmz1t, sl-webdmz2d, sl-webdmz2i, sl-webdmz2t, sl-bsiccc1t, sl-bsiccc2ti'"

  - name: restart sssd if the configuration for sssd was modified
    systemd:
      state: restarted
      name: sssd
    when: sssd_modified is changed
