---

# Put cspire-repo configs in place from templates

  - name: upload cspire-content-for-redhat-7.6.repo from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/cspire_repo_conf/templates/cspire-content-for-redhat-7.6_repo.j2"
      dest: /etc/yum.repos.d/cspire-content-for-redhat-7.6.repo
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: unconfined_u
      serole: object_r
      setype: system_conf_t
      selevel: s0
    when: ansible_distribution == 'RedHat' and ansible_distribution_version == '7.6'

  - name: upload cspire-content-for-redhat-7.7.repo from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/cspire_repo_conf/templates/cspire-content-for-redhat-7.7_repo.j2"
      dest: /etc/yum.repos.d/cspire-content-for-redhat-7.7.repo
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: unconfined_u
      serole: object_r
      setype: system_conf_t
      selevel: s0
    when: ansible_distribution == 'RedHat' and ansible_distribution_version == '7.7'
