---

# Put a nsswitch.conf in place from template

  - name: upload nsswitch.conf from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/nsswitch_conf/templates/nsswitch_conf.j2"
      dest: /etc/nsswitch.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
