---

# Put configuration into place using templates

  - name: upload /etc/rwtab.d/logrotate into place from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/rwtab_conf/templates/logrotate.j2"
      dest: /etc/rwtab.d/logrotate
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0

  - name: upload /etc/rwtab.d/sssd into place from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/rwtab_conf/templates/sssd.j2"
      dest: /etc/rwtab.d/sssd
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0

