---

# Put authconfig in place from template

  - name: upload authconfig from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/authconfig_conf/templates/authconfig_conf.j2"
      dest: /etc/sysconfig/authconfig
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
