---

# Put a krb5.conf in place from template

  - name: upload krb5.conf from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/krb5_conf/templates/krb5_conf.j2"
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: krb5_conf_t
      selevel: s0
    register: krb5_conf_modified

...
