---

# Put a chrony.conf in place from template

  - name: upload chrony.conf from template
    template:
      src: "{{ RoleDir }}/verify_configs/roles/chrony_conf/templates/chrony_conf.j2"
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: '0644'
      force: yes
      backup: yes
      seuser: system_u
      serole: object_r
      setype: etc_t
      selevel: s0
